services:
  - type: web
    name: aanyaa-telegram-bot
    env: python
    plan: free
    buildCommand: pip install --upgrade pip && pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: A4F_API_KEY
        sync: false
